sudo: false

language: node_js
node_js:
  - 'node'
script:
  -npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $SHA256:41CVsrgRUQa7LMsmd0gMWrZkwYUUcGhQdL6Kd2tsYW4
  on:
    branch: master
